baseURL = "https://jstoerig.com/"
languageCode = "en-gb"
title = "Julian's Lab"
theme = "PaperMod"

[params]
  defaultTheme = "light"
  disableThemeToggle = false
  ShowReadingTime = false
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowToc = true
  TocOpen = false
  math = true

[params.homeInfoParams]
  Title = "Julian's Lab"
  Content = "RF engineering, radio astronomy and miscellanea."

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 20

[[menu.main]]
  identifier = "impressum"
  name = "Impressum"
  url = "/impressum/"
  weight = 90

[[menu.main]]
  identifier = "privacy"
  name = "Privacy"
  url = "/privacy/"
  weight = 100
